### ISSUE TITLE
FR: Add filter_entry

### ISSUE THREAD

**Issue by turbo** [jessegrosjean/jwalk#10]
Thanks for jwalk! I might have missed it, but if it isn't there already, I'd appreciate a `filter_entry` method similar to WalkDir proper.

**Comment by jessegrosjean** [comment]
I think you can do with with [`process_entries`](https://docs.rs/jwalk/0.4.0/jwalk/struct.WalkDir.html#method.process_entries)
?

It's a bit more involved (but offers more flexibility). You are given a mutable Vector of entries:

1. To filter an entry out remove it from the Vec
2. Reorder the Vec to change the order of how the entries will be enumerated
3. If you want to return a directory entry, but not descend into it's contents use `entry.content_spec = None`.
