### ISSUE TITLE
issue with using / as the default name

### ISSUE THREAD

**Issue by bootandy** [jessegrosjean/jwalk#13]
Firstly thanks for building jwalk.

I am having a problem with jwalk.

The problem is here [there may be other places too]:
https://github.com/jessegrosjean/jwalk/blob/17ddb917a12d3e9787b6cbb2ace28758a712a95e/src/core/dir_entry.rs#L72

This makes a filename or defaults to '/'. The problem is in defaulting to '/'

```
    let mut iter = WalkDir::new(".");
    for entry in iter {
        if let Ok(e) = entry {
            println!("e: {:?}", e.file_name);
        }
    }
```
Will show e.file_name as '/'

```
    let mut iter = WalkDir::new("../tmp");
    for entry in iter {
        if let Ok(e) = entry {
            println!("e: {:?}", e);
        }
    }
```
The same directory ^ here shows the e.file_name as 'tmp'.

Running the same code with burntsushi's walkdir crate:
```
extern crate walkdir;
use walkdir::WalkDir;
    let mut iter = WalkDir::new(".");
    for entry in iter {
        if let Ok(e) = entry {
            println!("e: {:?}", e.file_name());
        }
    }
```
This gives '.' as the file_name.

therefore I think the correct thing to do here is to emulate the original WalkDir crate and the name should be '.'

What are your thoughts?
Thanks

**Comment by jessegrosjean** [comment]
I think this is fixed in 0.5.1
