### ISSUE TITLE
jwalk appears to swallow PermissionDenied

### ISSUE THREAD

**Issue by ratmice** [jessegrosjean/jwalk#4]
I was playing with converting the app i'm working on from walkdir to jwalk,
In figuring i should probably look at the error formatting. I noticed that jwalk
seems to swallow up PermissionDenied type errors, when failing to descend
into a directory where walkdir seems to emit them.

I'm not sure but just reading the code, it could be happening at
https://github.com/jessegrosjean/jwalk/blob/master/src/lib.rs#L178

The directory still ends up being listed, it just doesn't descend.

I should note: this appears to happen with both WalkDir::new("./no_permission_dir") as well as
WalkDir::new(".") when no_permission_dir/ is a subdirectory.

**Comment by jessegrosjean** [comment]
Thanks for the report.

Looking into this and I think it is working as intended when the unreadable directory is a subdirectory. In that case the directory is included in the results, but it has `dir_entry.content_error` set to the underlying permissions error.

But when the unreadable directory is the root of the traversal it looks like that `content_error` isn't getting set. I'll try to fix that soon.

**Comment by jessegrosjean** [comment]
> I'm not sure but just reading the code, it could be happening at
> https://github.com/jessegrosjean/jwalk/blob/master/src/lib.rs#L178

I think that part is working correctly. It is saying that a read of the dir entries content should only be scheduled (that's what a content_spec is, a scheduled read) if the dir_entry is a directory. If it's not a directory, or if there was an error reading the file type then don't schedule content read.

In the case where there was an error reading the file type a DirEntry is returned, but the file_type value is set to the underlying error.

**Comment by ratmice** [comment]
Thanks, I had indeed overlooked the existence of the content_error field of DirEntry,
and assumed that such errors would up as part of the iteration results
